export const SIGN_IN = 'SIGN_IN';

export const GET_HOME = 'GET_HOME';
export const GET_HOME_VISION = 'GET_HOME_VISION';
export const GET_HOME_FEATURE = 'GET_HOME_FEATURE';
export const GET_HOME_FEATURE_DETAIL = 'GET_HOME_FEATURE_DETAIL';
export const GET_HOME_SOCIAL_MEDIA = 'GET_HOME_SOCIAL_MEDIA';
export const GET_HOME_EVALUATE = 'GET_HOME_EVALUATE';
export const GET_HOME_OFFER = 'GET_HOME_OFFER';

export const GET_ALL_INSURANCE = 'GET_ALL_INSURANCE';
export const GET_ALL_ONWER_INSURANCE = 'GET_ALL_ONWER_INSURANCE';
export const GET_ALL_DEALER_INSURANCE = 'GET_ALL_DEALER_INSURANCE';
export const GET_INSURANCE_IS_ACTIVE = 'GET_INSURANCE_IS_ACTIVE';

export const GET_ALL_DISCOUNT_NEWS_BY_CATEGORY_ID = 'GET_ALL_DISCOUNT_NEWS_BY_CATEGORY_ID';
export const GET_ALL_PRODUCT_NEWS_BY_CATEGORY_ID = 'GET_ALL_PRODUCT_NEWS_BY_CATEGORY_ID';
export const GET_ALL_EVENT_NEWS_BY_CATEGORY_ID = 'GET_ALL_EVENT_NEWS_BY_CATEGORY_ID';

export const GET_ALL_FEATURE_INSTRUCTIONS_BY_CATEGORY_ID = 'GET_ALL_FEATURE_INSTRUCTIONS_BY_CATEGORY_ID';
export const GET_ALL_SETUP_INSTRUCTIONS_BY_CATEGORY_ID = 'GET_ALL_SETUP_INSTRUCTIONS_BY_CATEGORY_ID';

export const GET_ALL_SHIPPERS = 'GET_ALL_SHIPPERS';
export const CREATE_SUCCESSFULLY = 'CREATE_SUCCESSFULLY';
export const CREATE_FAILURE = 'CREATE_FAILURE';
export const LIST_HUB = 'LIST_HUB';
export const LOAD_PRODUCT_LIST = 'LOAD_PRODUCT_LIST';
export const LOAD_PROVIDER = 'LOAD_PROVIDER';
export const LOAD_PROVIDER_NAME = 'LOAD_PROVIDER_NAME';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const CHANGE_KEYWORD = 'CHANGE_KEYWORD';
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const CREATE_HUB = 'CREATE_HUB';
export const LOAD_SHIPPER = 'LOAD_SHIPPER';
export const LOAD_PRODUCTS_AVAILABLE = 'LOAD_PRODUCTS_AVAILABLE';
export const LOAD_FEATURE = 'LOAD_FEATURE';
export const CHANGE_ASSIGN_HUB_STATUS = 'CHANGE_ASSIGN_HUB_STATUS';
export const CHANGE_ASSIGN_ORDER_TO_SHIPPER_STATUS = 'CHANGE_ASSIGN_ORDER_TO_SHIPPER_STATUS';